version: v0.1
server:
  address: 0.0.0.0
  port: 8081
  socket: "/var/run/sysadm.sock"
log:
  accessLog: "logs/sysadm-access.log"
  errorLog: "logs/sysadm-error.log"
  kind: "text"
  level: "debug"
  splitAccessAndError: true
  timeStampFormat: ""
user:
  defaultUser: "admin"
  defaultPassword: "Sysadm12345"
DB:
  type: "postgre" 
  host: "172.17.0.4"
  port: 30432
  user: sysadm
  password: "Zaq12wsX"
  dbname: "sysadm"
  sslmode: "disable"
  sslrootcert: ""
  sslkey: ""
  sslcert: ""
