version: v0.1
server:
  address: "0.0.0.0"
  port: 8081
  socket: "/opt/sysadm/run/sysadm.sock"
  tls: false
  ca: ""
  cert: ""
  key: "" 
apiServer:
  apiVersion: "v1.0"
  address: "172.28.2.4"
  port: 8081
  tls: false
  ca: ""
  cert: ""
  key: ""
log:
  accessLog: "logs/sysadm-access.log"
  errorLog: "logs/sysadm-error.log"
  kind: "text"
  level: "debug"
  splitAccessAndError: true
  timeStampFormat: ""
user:
  defaultUser: "admin"
  defaultPassword: "Sysadm12345"
DB:
  type: "mysql" 
  host: "172.28.1.10"
  port: 30306
  user: sysadm
  password: "Sysadm12345"
  dbname: "sysadm"
  sslmode: "disable"
  sslrootcert: ""
  sslkey: ""
  sslcert: ""
registryctl:
  apiVersion: "v1.0"
  address: "172.28.2.4"
  port: 5001
  tls: false
  ca: ""
  cert: ""
  key: ""
