version: "{build}"
platform: x64
clone_folder: sysadm/sysadmLog
environment:
  GOPATH: c:\gopath
branches:
  only:
    - master
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
build_script:
  - go get -t
  - go test
