apiVersion: v1
kind: Secret
metadata:
  name: registry
  labels:
    app: registry
  namespace: sysadm
type: Opaque
data:
  passwd: c3lzYWRtX3JlZ2lzdHJ5X3VzZXI6JDJhJDEwJERiYmZYdnk0OEt2cXYyZEdxOHVXV2VJWnhzNFBTMlhsVXI4OEdacExaNVZTWnZOUHNOdmxl
