apiVersion: v1
kind: Service
metadata:
  name: "registry"
  labels:
    app: registry
  namespace: sysadm
spec:
  type: ClusterIP
  ports:
    - port: 
      port: 5000
      targetPort: 5000
  selector:
    app: registry
    component: registry
