apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: test
spec:
  completions: 5
  parallelism: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: hb.sysadm.cn/os/centos:centos7.9.2009
        imagePullPolicy: IfNotPresent
        name: nginx
        command: ["/usr/bin/sleep","60"]
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      restartPolicy: OnFailure
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: "Exists"
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: "Exists"