apiVersion: v1
kind: PersistentVolume
metadata:
  name: testmysql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/k8ssysadm/pvs/mysql
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
