apiVersion: v1
kind: Service
metadata:
  name: "sysadm"
  labels:
    app: sysadm
  namespace: sysadm
spec:
  type: ClusterIP
  ports:
    - name: http 
      port: 8080
      targetPort: 8080
  selector:
    app: sysadm
    component: sysadm
