apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  name: redis
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi 
  hostPath:
    path: /data/k8ssysadm/pvs/redis
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
