apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: sysadm
  labels:
    app: redis
    component: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
      component: redis
  template:
    metadata:
      labels:
        app: redis
        component: redis
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - name: redis
        image: hb.sincerecloud.com/application/redis:v2.4.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis
